
int const REVERSE_GRIP_ARM = 955, REVERSE_GRIP_WRIST = 460;
int const CARRY_BLOCKS_CLAW = -31, CARRY_BLOCKS_ARM = 100, CARRY_BLOCKS_WRIST = 423;
int const PICKUP_BLOCK_CLAW = -30, FULL_OPEN_CLAW = -145, WHEEL_WELL_OPEN_CLAW = -87;
int const STACK_BLOCKS_LOW_WRIST = 250, STOP_WHEELS = 0, STOP_ARM = 0;
int const	STACK_BLOCKS_LOW_ARM = 40;

int const AIM_BLOCKS_HIGH_WRIST = 490;
int const	AIM_BLOCKS_HIGH_ARM = 243;
int const	AIM_REVERSE_GRIP_ARM = 750;

int const STACK_BLOCKS_HIGH_WRIST = 152;
int const	STACK_BLOCKS_HIGH_ARM = 243;

int const DRIFT_LEFT = -1, DRIFT_RIGHT = 1, DRIFT_MODERATE_RIGHT = 2, DRIFT_FAR_RIGHT = 3, STRAIGHT = 0;
